name: infrastructure

services:
  chatshare:
    image: ghcr.io/madhouseplatform/chatsharejs:latest
    stdin_open: true  # -i
    tty: true       # -t
    environment:
      EULA: TRUE
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './map.ts:/map.ts'
      - './env:/.env'
    networks:
      - default

networks:
  default:
    driver: bridge
